# Generated by Django 5.1.2 on 2024-11-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_blogitems_likes_blogcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogitems',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
